### ISSUE TITLE
What does the version of clang need? 

### ISSUE THREAD

**Issue by CaptainVi** [tov/libffi-sys-rs#13]
Hello!

I tried to compile lib and I had an error "thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments', ../.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.21.2/src/lib.rs:1456:1"
"error: failed to run custom build command for `libffi-sys v0.6.0 "

I have on 1st PC:
clang version 7.0.0 (trunk 326027) (llvm/trunk 326026)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/clang/bin

On another PC I have:
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

And it works.

**Comment by tov** [comment]
I don't know if that is because of the Clang version. Are you saying it works on the second PC but not the first? I don't know what Clang 7.0.0 is, since 5 is the highest version they've reached. Is it a vendor version number? I know Apple renumbers their Clangs.

**Comment by yorickpeterse** [comment]
Per https://github.com/tov/libffi-sys-rs/pull/37, we no longer need clang, so this issue can be closed.
