### ISSUE TITLE
Consider building without documentation

### ISSUE THREAD

**Issue by yorickpeterse** [tov/libffi-sys-rs#18]
The FFI README says the following:

> If you don't want to build documentation, use the --disable-docs configure switch.

libffi-sys-rs does not seem to be using this. I can't exactly figure it out, but this might remove the need for installing texinfo just to build libffi-sys-rs/libffi.

**Comment by tov** [comment]
Oh, that would be nice. I'll try that once the Windows stuff you're currently doing stabilizes. Thanks!

**Comment by yorickpeterse** [comment]
Fixed in https://github.com/tov/libffi-sys-rs/pull/19
