### ISSUE TITLE
libclang dependency was changed in a semver compatible update

### ISSUE THREAD

**Issue by ExpHP** [tov/libffi-sys-rs#21]
Please see https://github.com/rust-lang/cargo/issues/5237 .  Any update to a bindgen dependency that uses a new, semver-incompatible `clang-sys` dependency (such as libffi-sys's `0.6.4` update) is a breaking change due to this shortcoming of cargo.

`libffi-sys 0.6.4` should be yanked and rereleased as `libffi-sys 0.7.0`.

**Comment by tov** [comment]
Oh, that’s not good! Sorry about that. I'll fix it now.

**Comment by tov** [comment]
Okay, [yanked 0.6.4](https://crates.io/crates/libffi-sys/0.6.4) and re-released as [0.7.0](https://crates.io/crates/libffi-sys/0.7.0). Sorry for the trouble.
