### ISSUE TITLE
Bumping to dev version after release makes testing PRs more difficult

### ISSUE THREAD

**Issue by timfish** [tov/libffi-sys-rs#30]
Testing PRs to `libffi-sys` is difficult because the version in master does not match the version that you need to patch.

The standard way to test a PR for `libffi-sys` + `libffi` would be to patch using the PR branch:
```
[dependencies]
libffi = "0.9.0"

[patch.crates-io]
libffi-sys = { git = "https://github.com/timfish/libffi-sys-rs.git", branch = "msvc-build" }
```
However, this doesn't work because `[patch]` only works when the versions match. The PR branch (`msvc-build`) is based of master (`0.9.1-alpha.0`) and the version being patched is `0.9.0` so you'll get an error:
```
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  patch for `libffi-sys` in `https://github.com/rust-lang/crates.io-index` did not resolve to any crates.
```
This behaviour in `cargo-release` is a bit counterproductive!

**Comment by tov** [comment]
I see what you mean. I can think of workarounds, but nothing really satisfying. Do you have any ideas?

(Also, this seems like a problem that would apply to more crates than just this pair.)

**Comment by timfish** [comment]
I've opened an issue for discussion [here](https://github.com/sunng87/cargo-release/issues/199). My only suggestion so far is to make the final bump and push optional.

**Comment by timfish** [comment]
The maintainer of `cargo-release` suggests that this would not be an issue if `libffi-sys` and `libffi` crates were in a workspace. It would certainly aid testing the two together and simplify the CI build. 

Would you be open to a PR that moved `libffi-sys-rs` into the `libffi-rs` repository with a workspace and a single CI build?

**Comment by tov** [comment]
Yes, that sounds like a good idea to me. Thanks for offering. I haven’t yet used or read about workspaces, but if it solves your problem and seems appropriate then I’m open to it.

**Comment by yorickpeterse** [comment]
Wouldn't a simple solution be to just not bump the version until releasing a new one? It seems like this would be the least invasive change.

**Comment by yorickpeterse** [comment]
I propose that starting with the next release (aka from now on), we just don't pre-bump versions. This seems like the easiest fix.
